AWSTemplateFormatVersion: '2010-09-09'
Description: 'Launch EC2 with requirement url:https://spring2020.csye6225.cloud/assignments/05/#aws-networking-setup'
Parameters:
  AWSregion:
      Type: String
      Default: "us-east-1"
      Description: "s3bucket for deploy"
  DeployS3: 
      Type: String
      Default: "codedeploy.meepo.me"
      Description: "s3bucket for deploy"
  AccountID:
      Type: String
      Default: "512233003956 "
      Description: "AccountID"
  APPName:
      Type: String
      Default: "webapp"
      Description: "APPName"
  ComputePlatform:
      Type: String
      Default: "Server" #EC2
      AllowedValues:
      -   Server
      -   ECS
      -   Lambda
      Description: "ComputePlatform for codedeploy"
  DeploymentGroupName:
      Type: String
      Default: "csye-6225"
      Description: "DeploymentGroupName for codedeploy"
  DeploymentType:
      Type: String
      Default: "IN_PLACE"
      AllowedValues:
      -   IN_PLACE
      -   BLUE_GREEN
      Description: "DeploymentType"
Resources:
  CodeDeployServiceRole: 
      Type: AWS::IAM::Role
      Properties: 
          RoleName: CodeDeployServiceRole
          ManagedPolicyArns: 
            -   arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
          AssumeRolePolicyDocument: 
              Version: '2012-10-17'
              Statement: 
              -   Effect: Allow
                  Sid: ""
                  Principal: 
                      Service: 
                      -   ec2.amazonaws.com 
                      -   codedeploy.amazonaws.com 
                  Action: 
                  -   'sts:AssumeRole'
  CircleCIEc2Ami:
      Type: 'AWS::IAM::ManagedPolicy'
      Properties: 
          ManagedPolicyName: circleci-ec2-ami
          Users:
          -   cicd
          PolicyDocument: 
              Version: "2012-10-17"
              Statement: 
              -   Effect: "Allow"
                  Action: 
                  -   "ec2:AttachVolume"
                  -   "ec2:AuthorizeSecurityGroupIngress"
                  -   "ec2:CopyImage"
                  -   "ec2:CreateImage"
                  -   "ec2:CreateKeypair"
                  -   "ec2:CreateSecurityGroup"
                  -   "ec2:CreateSnapshot"
                  -   "ec2:CreateTags"
                  -   "ec2:CreateVolume"
                  -   "ec2:DeleteKeyPair"
                  -   "ec2:DeleteSecurityGroup"
                  -   "ec2:DeleteSnapshot"
                  -   "ec2:DeleteVolume"
                  -   "ec2:DeregisterImage"
                  -   "ec2:DescribeImageAttribute"
                  -   "ec2:DescribeImages"
                  -   "ec2:DescribeInstances"
                  -   "ec2:DescribeInstanceStatus"
                  -   "ec2:DescribeRegions"
                  -   "ec2:DescribeSecurityGroups"
                  -   "ec2:DescribeSnapshots"
                  -   "ec2:DescribeSubnets"
                  -   "ec2:DescribeTags"
                  -   "ec2:DescribeVolumes"
                  -   "ec2:DetachVolume"
                  -   "ec2:GetPasswordData"
                  -   "ec2:ModifyImageAttribute"
                  -   "ec2:ModifyInstanceAttribute"
                  -   "ec2:ModifySnapshotAttribute"
                  -   "ec2:RegisterImage"
                  -   "ec2:RunInstances"
                  -   "ec2:StopInstances"
                  -   "ec2:TerminateInstances"
                      
                  "Resource": "*"
  CircleCIUploadToS3:
      Type: 'AWS::IAM::ManagedPolicy'
      Properties: 
          ManagedPolicyName: CircleCI-Upload-To-S3
          Users:
          -   cicd
          PolicyDocument: 
              Version: "2012-10-17"
              Statement: 
              -   Effect: "Allow"
                  Action: 
                  -   "s3:PutObject"
                  -   "s3:GetObject"
                  -   "s3:ListBucket"
                  Resource: 
                  -   !Join
                      -   ''
                      -   -   'arn:aws:s3:::'
                          -   !Ref DeployS3
                  -   !Join
                      -   ''
                      -   -   'arn:aws:s3:::'
                          -   !Ref DeployS3
                          -   '/*'
  CircleCICodeDeploy:
      Type: 'AWS::IAM::ManagedPolicy'
      Properties: 
          ManagedPolicyName: CircleCI-Code-Deploy
          Users:
          -   cicd
          PolicyDocument: 
              Version: "2012-10-17"
              Statement: 
              -   Effect: "Allow"
                  Action: 
                  -   "codedeploy:RegisterApplicationRevision"
                  -   "codedeploy:GetApplicationRevision"
                  Resource: 
                  -   !Join
                      -   ''
                      -   -   'arn:aws:codedeploy:'
                          -   !Ref AWSregion
                          -   ':'
                          -   !Ref AccountID
                          -   ':application:'
                          -   !Ref APPName
              -   Effect: "Allow"
                  Action: 
                  -   "codedeploy:CreateDeployment"
                  -   "codedeploy:GetDeployment"
                  Resource: 
                  -   "*"
              -   Effect: "Allow"
                  Action: 
                  -   "codedeploy:GetDeploymentConfig"
                  Resource: 
                  -   !Join
                      -   ''
                      -   -   'arn:aws:codedeploy:'
                          -   !Ref AWSregion
                          -   ':'
                          -   !Ref AccountID
                          -   ':deploymentconfig:CodeDeployDefault.OneAtATime'
                  -   !Join
                      -   ''
                      -   -   'arn:aws:codedeploy:'
                          -   !Ref AWSregion
                          -   ':'
                          -   !Ref AccountID
                          -   ':deploymentconfig:CodeDeployDefault.HalfAtATime'
                  -   !Join
                      -   ''
                      -   -   'arn:aws:codedeploy:'
                          -   !Ref AWSregion
                          -   ':'
                          -   !Ref AccountID
                          -   ':deploymentconfig:CodeDeployDefault.AllAtOnce'
  Application:
      Type: AWS::CodeDeploy::Application
      Properties:
          ApplicationName: !Ref APPName
          ComputePlatform: !Ref ComputePlatform
  DeploymentGroup:
      DependsOn: 
      -   Application
      -   CodeDeployServiceRole
      Type: AWS::CodeDeploy::DeploymentGroup
      Properties:
          ApplicationName: !Ref APPName
          DeploymentGroupName: !Ref DeploymentGroupName
          Ec2TagFilters:
          -   Key: name
              Value: demo
              Type: KEY_AND_VALUE 
          DeploymentStyle:
              DeploymentOption: WITHOUT_TRAFFIC_CONTROL
              DeploymentType: !Ref DeploymentType
          AutoRollbackConfiguration:
              Enabled : true
              Events: 
              -   DEPLOYMENT_FAILURE
          ServiceRoleArn: 
              !GetAtt CodeDeployServiceRole.Arn
          DeploymentConfigName: CodeDeployDefault.AllAtOnce